import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.geoScore': 'GEO Score',
    'nav.schemaAudit': 'Schema Audit',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.bookCall': 'Book a call',

    // Hero Section
    'hero.badge': 'GEO Agency — Generative Engine Optimization',
    'hero.title': 'Get ',
    'hero.titleHighlight': 'cited',
    'hero.titleEnd': ' by',
    'hero.titleEnd2': 'AI engines.',
    'hero.subtitle': 'We optimize your visibility in ChatGPT, Perplexity and Google AI to generate qualified leads without relying on advertising.',
    'hero.cta': 'Test your score',
    'hero.ctaSecondary': 'Talk to an expert',
    'hero.stat1Value': '40%',
    'hero.stat1Label': 'AI searches',
    'hero.stat2Value': '200M+',
    'hero.stat2Label': 'ChatGPT users',
    'hero.stat3Value': '8x',
    'hero.stat3Label': 'Average ROI',

    // Stats Section
    'stats.title': 'Traditional SEO is no longer enough.',
    'stats.subtitle': "40% of searches now go through AI. If you don't appear in their answers, you're invisible.",
    'stats.stat1Value': '0%',
    'stats.stat1Label': 'Current AI visibility',
    'stats.stat1Desc': 'Most websites never appear in ChatGPT or Perplexity answers.',
    'stats.stat2Value': '30%',
    'stats.stat2Label': 'Organic clicks',
    'stats.stat2Desc': "Google's AI Overviews drastically reduce clicks to websites.",
    'stats.stat3Value': '200M',
    'stats.stat3Label': 'ChatGPT users',
    'stats.stat3Desc': 'A massive market looking for recommendations. Are you recommended?',
    'stats.cta': 'Check your score',

    // Services Section
    'services.badge': 'What we do',
    'services.title': 'A proven methodology to make you visible in the ',
    'services.titleHighlight': 'generative AI era.',
    'services.service1Title': 'GEO Audit',
    'services.service1Subtitle': 'Complete analysis of your current visibility in AI engines and opportunity identification.',
    'services.service1Feature1': 'Testing on 50+ key queries',
    'services.service1Feature2': 'AI competitive analysis',
    'services.service1Feature3': 'Detailed GEO score',
    'services.service1Feature4': 'Personalized roadmap',
    'services.service2Title': 'Technical Optimization',
    'services.service2Subtitle': 'Implementation of structured data and technical optimizations for LLMs.',
    'services.service2Feature1': 'Advanced Schema.org',
    'services.service2Feature2': 'AI-friendly content structure',
    'services.service2Feature3': 'E-E-A-T optimization',
    'services.service2Feature4': 'Technical performance',
    'services.service3Title': 'GEO Content',
    'services.service3Subtitle': 'Creation and optimization of content designed to be cited by artificial intelligence.',
    'services.service3Feature1': 'Citation-ready articles',
    'services.service3Feature2': 'Optimized FAQs',
    'services.service3Feature3': 'Data and sources',
    'services.service3Feature4': 'Structured Q&A format',
    'services.viewAll': 'View all services',

    // Process Section
    'process.badge': 'Our process',
    'process.title': 'A clear 4-step methodology',
    'process.titleHighlight': 'for measurable results.',
    'process.step1Title': 'Audit',
    'process.step1Desc': 'Analysis of your current AI visibility',
    'process.step2Title': 'Strategy',
    'process.step2Desc': 'Personalized action plan',
    'process.step3Title': 'Execution',
    'process.step3Desc': 'Technical and content optimization',
    'process.step4Title': 'Measure',
    'process.step4Desc': 'Tracking and continuous improvement',
    'process.cta': 'Check your score',

    // Results Section
    'results.badge': 'Concrete results',
    'results.title': 'Our clients see their AI visibility',
    'results.titleHighlight': 'take off within weeks.',
    'results.result1Label': 'Average AI mentions',
    'results.result1Desc': 'Increase in brand citations across AI platforms',
    'results.result2Label': 'Key queries covered',
    'results.result2Desc': 'Strategic search terms optimized for visibility',
    'results.result3Label': 'Qualified traffic',
    'results.result3Desc': 'Growth in high-intent visitor engagement',
    'results.result4Label': 'Average ROI observed',
    'results.result4Desc': 'Return on investment multiplier',

    // CTA Section
    'cta.title': 'Is your brand ',
    'cta.titleHighlight': 'invisible to AI?',
    'cta.subtitle': 'Discover your GEO Score in 30 seconds. Free, no commitment.',
    'cta.button': 'Check my score',
    'cta.callTitle': 'Book your discovery call.',
    'cta.callSubtitle': '30 minutes to analyze your situation and define a GEO strategy adapted to your goals.',
    'cta.benefit1': 'Audit of your current AI visibility',
    'cta.benefit2': 'Competitor analysis',
    'cta.benefit3': 'Personalized recommendations',
    'cta.benefit4': 'Concrete action plan',
    'cta.benefit5': '100% free, no commitment',
    'cta.contactDirect': 'Or contact us directly:',
    'cta.bookCall': 'Book a call',

    // Pricing Section
    'pricing.badge': 'Our plans',
    'pricing.title': 'Packages tailored to your ',
    'pricing.titleHighlight': 'needs and budget.',
    'pricing.popular': 'Popular',
    'pricing.viewDetails': 'View details',
    'pricing.hideDetails': 'Hide details',
    'pricing.bookCall': 'Book a call',
    'pricing.starter': 'Starter',
    'pricing.starterSubtitle': 'Get started with GEO',
    'pricing.starterPrice': '$2,000',
    'pricing.starterPeriod': 'One-shot + $450/mo maintenance',
    'pricing.starterFeature1': 'GEO Audit (5 AI providers, ~90 prompts, 1 language)',
    'pricing.starterFeature2': 'Audit report with GEO score + benchmark',
    'pricing.starterFeature3': 'Schema.org — 3 blocks',
    'pricing.starterFeature4': '6 GEO-optimized pillar articles (1 language)',
    'pricing.starterFeature5': 'Priority recommendations',
    'pricing.starterFeature6': 'Maintenance: monthly monitoring + tracking report',
    'pricing.growth': 'Growth',
    'pricing.growthSubtitle': 'Full support package',
    'pricing.growthPrice': '$4,000',
    'pricing.growthPeriod': 'One-shot + $600/mo maintenance',
    'pricing.growthFeature1': 'Extended GEO Audit (~150 prompts, 3 languages)',
    'pricing.growthFeature2': 'Full audit report',
    'pricing.growthFeature3': 'Schema.org — 3 blocks + site implementation',
    'pricing.growthFeature4': '18 pillar articles (6 per language, 3 languages)',
    'pricing.growthFeature5': 'GEO content plan',
    'pricing.growthFeature6': 'Maintenance: monitoring + content optimization + monthly report',
    'pricing.custom': 'Custom',
    'pricing.customSubtitle': 'Tailored projects',
    'pricing.customPrice': '$6,000+',
    'pricing.customPeriod': 'Custom',
    'pricing.customFeature1': 'Multi-site / multi-brand',
    'pricing.customFeature2': 'Volume >20 articles/month',
    'pricing.customFeature3': 'Wikipedia strategy',
    'pricing.customFeature4': 'Team training',
    'pricing.customFeature5': 'GEO press relations',
    'pricing.customFeature6': 'Dedicated consultant',

    // Contact Section (form on landing page)
    'contactSection.badge': 'Free audit request',
    'contactSection.title': "Fill out this form and we'll get back to you within ",
    'contactSection.titleHighlight': '24 hours.',
    'contactSection.thankYou': 'Thank you!',
    'contactSection.received': "We've received your request and will get back to you within 24 hours.",
    'contactSection.firstName': 'First name',
    'contactSection.lastName': 'Last name',
    'contactSection.email': 'Professional email',
    'contactSection.website': 'Website',
    'contactSection.budget': 'Monthly budget',
    'contactSection.goal': 'Your main goal',
    'contactSection.goalPlaceholder': 'Tell us about your goals and challenges...',
    'contactSection.submit': 'Request my free audit',
    'contactSection.budgetOption1': 'Select...',
    'contactSection.budgetOption2': 'Starter — $2,000 + $450/mo',
    'contactSection.budgetOption3': 'Growth — $4,000 + $600/mo',
    'contactSection.budgetOption4': 'Custom — from $6,000',

    // Contact Page
    'contact.tagline': 'Contact',
    'contact.title': "Let's talk about your ",
    'contact.titleHighlight': 'AI visibility.',
    'contact.subtitle': 'Get a free consultation and discover how we can help your brand get cited by AI engines.',
    'contact.email': 'Email',
    'contact.emailCopied': 'Email copied!',
    'contact.bookCall': 'Book a call',
    'contact.scheduleMeeting': 'Schedule a meeting',
    'contact.formTitle': 'Send us a message',
    'contact.formSubtitle': "Fill out the form below and we'll get back to you shortly.",
    'contact.firstName': 'First name',
    'contact.lastName': 'Last name',
    'contact.professionalEmail': 'Professional email',
    'contact.website': 'Website',
    'contact.budget': 'Monthly budget',
    'contact.goal': 'Your main goal',
    'contact.goalPlaceholder': 'Tell us about your goals and challenges...',
    'contact.send': 'Send message',
    'contact.sending': 'Sending...',
    'contact.thankYou': 'Thank you!',
    'contact.received': "We've received your message and will get back to you within 24 hours.",
    'contact.error': 'Something went wrong. Please try again.',
    'contact.budgetOption1': 'Select...',
    'contact.budgetOption2': 'Starter — $2,000 + $450/mo',
    'contact.budgetOption3': 'Growth — $4,000 + $600/mo',
    'contact.budgetOption4': 'Custom — from $6,000',

    // GEO Score Page
    'geoScore.tagline': 'GEO Score',
    'geoScore.title': 'How visible are you to ',
    'geoScore.titleHighlight': 'AI engines?',
    'geoScore.subtitle': 'Get your free GEO Score in seconds. Discover how well your website is optimized for ChatGPT, Perplexity, and other AI systems.',
    'geoScore.brandLabel': 'Your brand / company name',
    'geoScore.brandPlaceholder': 'Ex: Cited, Nike, Salesforce...',
    'geoScore.industryLabel': 'Industry',
    'geoScore.industrySelect': 'Select your industry',
    'geoScore.websiteLabel': 'Website',
    'geoScore.websiteOptional': '(optional)',
    'geoScore.websiteHint': "We'll use it to refine the analysis",
    'geoScore.websitePlaceholder': 'https://your-site.com',
    'geoScore.analyze': 'Analyze my AI visibility',
    'geoScore.analyzing': 'Analyzing...',
    'geoScore.getAudit': 'Get a detailed audit',
    'geoScore.checkAnother': 'Check another brand',
    'geoScore.scoreExcellent': 'Excellent! Your site is well-optimized for AI.',
    'geoScore.scoreGood': "Good start, but there's room for improvement.",
    'geoScore.scoreNeedsWork': 'Your site needs significant optimization for AI visibility.',
    'geoScore.whatWeCheck': 'What we check',
    'geoScore.weight': 'Weight',
    'geoScore.improveTitle': 'Want to improve your score?',
    'geoScore.improveSubtitle': 'Our experts can help you optimize your site for maximum AI visibility.',
    'geoScore.explorServices': 'Explore our services',
    'geoScore.industryTechnology': 'Technology',
    'geoScore.industrySaas': 'SaaS',
    'geoScore.industryEcommerce': 'E-commerce',
    'geoScore.industryFinance': 'Finance',
    'geoScore.industryHealthcare': 'Healthcare',
    'geoScore.industryConsulting': 'Consulting',
    'geoScore.industryAgency': 'Agency',
    'geoScore.industryEducation': 'Education',
    'geoScore.industryRealEstate': 'Real Estate',
    'geoScore.industryOther': 'Other',

    // Schema Audit Page
    'schemaAudit.tagline': 'Schema Audit',
    'schemaAudit.title': 'Make your content ',
    'schemaAudit.titleHighlight': 'understandable by AI.',
    'schemaAudit.subtitle': 'Schema.org markup is the foundation of AI visibility. We audit, implement, and optimize structured data to help AI engines understand and cite your content.',
    'schemaAudit.analyzeTitle': 'Analyze your Schema.org',
    'schemaAudit.analyzeSubtitle': 'Enter your URL to get a free schema audit',
    'schemaAudit.urlPlaceholder': 'https://your-website.com',
    'schemaAudit.analyze': 'Analyze Schema.org',
    'schemaAudit.analyzing': 'Analyzing...',
    'schemaAudit.stepFetching': 'Fetching page',
    'schemaAudit.stepDetecting': 'Detecting schemas',
    'schemaAudit.stepAnalyzing': 'Analyzing markup',
    'schemaAudit.stepCalculating': 'Calculating score',
    'schemaAudit.scoreExcellent': 'Excellent! Your Schema.org is well-implemented.',
    'schemaAudit.scoreGood': "Good start, but there's room for improvement.",
    'schemaAudit.scoreNeedsWork': 'Your site needs significant Schema.org optimization.',
    'schemaAudit.schemasDetected': 'Schemas detected',
    'schemaAudit.issuesFound': 'Issues found',
    'schemaAudit.emailReportText': 'Get a detailed PDF report sent to your email',
    'schemaAudit.emailPlaceholder': 'your@email.com',
    'schemaAudit.sendReport': 'Send report',
    'schemaAudit.reportSent': 'Report sent to',
    'schemaAudit.bookCall': 'Book a free call',
    'schemaAudit.analyzeAnother': 'Analyze another URL',
    'schemaAudit.featuresTitle1': 'Schema.org Implementation',
    'schemaAudit.featuresDesc1': 'Complete structured data markup for AI understanding',
    'schemaAudit.featuresTitle2': 'Validation & Testing',
    'schemaAudit.featuresDesc2': 'Ensure your markup is error-free and optimized',
    'schemaAudit.featuresTitle3': 'Performance Impact',
    'schemaAudit.featuresDesc3': 'Measure the effect on AI visibility',
    'schemaAudit.featuresTitle4': 'Quick Implementation',
    'schemaAudit.featuresDesc4': 'Get started in days, not weeks',
    'schemaAudit.schemaTypesTitle': 'Schema Types We Implement',
    'schemaAudit.schemaTypesSubtitle': 'Comprehensive coverage of all relevant structured data types',
    'schemaAudit.processTitle': 'Our Process',
    'schemaAudit.processSubtitle': 'A systematic approach to Schema.org optimization',
    'schemaAudit.processStep1': 'Audit',
    'schemaAudit.processStep1Desc': 'Analyze current Schema.org implementation',
    'schemaAudit.processStep2': 'Strategy',
    'schemaAudit.processStep2Desc': 'Identify missing markup opportunities',
    'schemaAudit.processStep3': 'Implementation',
    'schemaAudit.processStep3Desc': 'Add and optimize structured data',
    'schemaAudit.processStep4': 'Validation',
    'schemaAudit.processStep4Desc': 'Test and verify all markup',
    'schemaAudit.pricingTitle': 'Pricing',
    'schemaAudit.pricingSubtitle': 'Choose the package that fits your needs',
    'schemaAudit.pricingStarter': 'Starter',
    'schemaAudit.pricingStarterDesc': '3 schema types',
    'schemaAudit.pricingStarterPrice': '$1,500',
    'schemaAudit.pricingGrowth': 'Growth',
    'schemaAudit.pricingGrowthDesc': '8 schema types',
    'schemaAudit.pricingGrowthPrice': '$3,000',
    'schemaAudit.pricingEnterprise': 'Enterprise',
    'schemaAudit.pricingEnterpriseDesc': 'Unlimited types',
    'schemaAudit.pricingEnterprisePrice': 'Custom',
    'schemaAudit.mostPopular': 'Most Popular',
    'schemaAudit.getStarted': 'Get started',
    'schemaAudit.ctaTitle': 'Ready to optimize your Schema.org?',
    'schemaAudit.ctaSubtitle': 'Get a free audit of your current structured data implementation.',
    'schemaAudit.ctaButton': 'Request free audit',

    // FAQ Page
    'faq.tagline': 'FAQ',
    'faq.title': 'Frequently asked ',
    'faq.titleHighlight': 'questions.',
    'faq.subtitle': 'Everything you need to know about GEO and our services.',
    'faq.catGeneral': 'General',
    'faq.catServices': 'Services',
    'faq.catPricing': 'Pricing',
    'faq.catTechnical': 'Technical',
    'faq.general1Q': 'What is Generative Engine Optimization (GEO)?',
    'faq.general1A': 'GEO is the practice of optimizing your website and content to be visible and cited by AI engines like ChatGPT, Perplexity, Claude, and Google AI. Unlike traditional SEO which focuses on ranking in search results, GEO focuses on being referenced in AI-generated answers.',
    'faq.general2Q': 'How is GEO different from SEO?',
    'faq.general2A': 'While SEO focuses on ranking in search engine results pages, GEO focuses on being cited by AI systems. This requires different strategies including structured data implementation, entity optimization, and content structured for AI comprehension.',
    'faq.general3Q': 'Why do I need GEO?',
    'faq.general3A': "40% of searches now go through AI systems. If your brand isn't visible in AI answers, you're missing a massive opportunity to reach potential customers. GEO ensures your business is recommended by AI systems.",
    'faq.services1Q': 'What services do you offer?',
    'faq.services1A': 'We offer three core services: GEO Audit (analysis of your AI visibility), Technical Optimization (Schema.org implementation and site structure), and GEO Content (creating AI-optimized content). We also offer custom enterprise solutions.',
    'faq.services2Q': 'How long does it take to see results?',
    'faq.services2A': 'Most clients start seeing increased AI mentions within 4-6 weeks, with significant improvements by month 3. The timeline depends on your starting point and the scope of work.',
    'faq.services3Q': 'Do you work with all industries?',
    'faq.services3A': 'We work with B2B companies, e-commerce, SaaS, professional services, and more. Our methodology is adaptable to any industry that relies on organic visibility.',
    'faq.pricing1Q': 'How much does GEO optimization cost?',
    'faq.pricing1A': 'Our Starter package begins at $2,000 + $450/month maintenance. Growth package is $4,000 + $600/month. We also offer custom enterprise solutions. Contact us for a personalized quote.',
    'faq.pricing2Q': "What's included in maintenance?",
    'faq.pricing2A': 'Maintenance includes monthly monitoring of your AI visibility, tracking reports, content optimization recommendations, and quarterly strategy reviews to ensure continued improvement.',
    'faq.pricing3Q': 'Is there a minimum contract?',
    'faq.pricing3A': 'Our initial engagement includes a one-time setup fee plus a 6-month minimum maintenance contract. After that, you can cancel with 30 days notice.',
    'faq.technical1Q': 'What is Schema.org and why does it matter?',
    'faq.technical1A': "Schema.org is a standardized vocabulary for structured data markup. It helps AI systems understand your content's context, entities, and relationships, making it more likely to be cited in AI-generated responses.",
    'faq.technical2Q': 'Do I need to change my website?',
    'faq.technical2A': 'Depending on the audit results, we may recommend technical changes to improve AI visibility. These typically involve adding structured data, optimizing content structure, and improving site performance.',
    'faq.technical3Q': 'Will GEO affect my traditional SEO?',
    'faq.technical3A': 'GEO and SEO are complementary. Many GEO optimizations (like Schema.org markup) also benefit traditional SEO. We ensure all changes maintain or improve your existing search rankings.',
    'faq.stillQuestions': 'Still have questions?',
    'faq.stillQuestionsSubtitle': "Can't find the answer you're looking for? Our team is here to help.",
    'faq.contactUs': 'Contact us',

    // Blog Page
    'blog.tagline': 'Blog',
    'blog.title': 'Insights on ',
    'blog.titleHighlight': 'AI visibility.',
    'blog.subtitle': 'The latest strategies, case studies, and insights on optimizing for generative AI engines.',
    'blog.featured': 'Featured',
    'blog.readArticle': 'Read article',
    'blog.latestArticles': 'Latest Articles',
    'blog.catAll': 'All',
    'blog.catGeoBasics': 'GEO Basics',
    'blog.catTechnical': 'Technical',
    'blog.catImplementation': 'Implementation',
    'blog.catCaseStudy': 'Case Study',
    'blog.catIndustry': 'Industry',
    'blog.stayUpdated': 'Stay updated',
    'blog.stayUpdatedSubtitle': 'Get the latest GEO insights delivered to your inbox.',
    'blog.emailPlaceholder': 'Enter your email',
    'blog.subscribe': 'Subscribe',
    'blog.subscribing': 'Subscribing...',
    'blog.subscribed': 'Thanks for subscribing!',
    'blog.article1Title': 'What is Generative Engine Optimization (GEO)?',
    'blog.article1Excerpt': 'Discover how GEO differs from traditional SEO and why it matters for your business in the AI era.',
    'blog.article1Category': 'GEO Basics',
    'blog.article1ReadTime': '5 min read',
    'blog.article1Date': 'Jan 15, 2026',
    'blog.article2Title': 'How ChatGPT Cites Websites: A Technical Deep Dive',
    'blog.article2Excerpt': 'Understanding the mechanisms behind AI citation and how to optimize your content for maximum visibility.',
    'blog.article2Category': 'Technical',
    'blog.article2ReadTime': '8 min read',
    'blog.article2Date': 'Jan 12, 2026',
    'blog.article3Title': 'Schema.org for AI: The Complete Guide',
    'blog.article3Excerpt': 'Learn how to implement structured data that helps AI systems understand and cite your content.',
    'blog.article3Category': 'Implementation',
    'blog.article3ReadTime': '12 min read',
    'blog.article3Date': 'Jan 8, 2026',
    'blog.article4Title': 'Case Study: How We Increased AI Mentions by 340%',
    'blog.article4Excerpt': 'A detailed breakdown of our strategy and the results we achieved for a B2B SaaS company.',
    'blog.article4Category': 'Case Study',
    'blog.article4ReadTime': '6 min read',
    'blog.article4Date': 'Jan 5, 2026',
    'blog.article5Title': 'The Future of Search: AI vs Traditional SEO',
    'blog.article5Excerpt': 'Why traditional SEO is no longer enough and how to prepare for the AI-first future.',
    'blog.article5Category': 'Industry',
    'blog.article5ReadTime': '7 min read',
    'blog.article5Date': 'Jan 2, 2026',
    'blog.article6Title': 'E-E-A-T Optimization for Large Language Models',
    'blog.article6Excerpt': 'How to build authority signals that AI systems recognize and trust.',
    'blog.article6Category': 'Technical',
    'blog.article6ReadTime': '10 min read',
    'blog.article6Date': 'Dec 28, 2025',

    // Pricing Page
    'pricingPage.tagline': 'Pricing',
    'pricingPage.title': 'Simple, transparent ',
    'pricingPage.titleHighlight': 'pricing.',
    'pricingPage.subtitle': 'Choose the plan that fits your needs. All plans include our core GEO methodology.',
    'pricingPage.mostPopular': 'Most Popular',
    'pricingPage.getStarted': 'Get started',
    'pricingPage.starter': 'Starter',
    'pricingPage.starterSubtitle': 'Get started with GEO',
    'pricingPage.starterPrice': '$2,000',
    'pricingPage.starterPeriod': 'One-shot + $450/mo maintenance',
    'pricingPage.starterFeature1': 'GEO Audit (5 AI providers, ~90 prompts, 1 language)',
    'pricingPage.starterFeature2': 'Audit report with GEO score + benchmark',
    'pricingPage.starterFeature3': 'Schema.org — 3 blocks',
    'pricingPage.starterFeature4': '6 GEO-optimized pillar articles (1 language)',
    'pricingPage.starterFeature5': 'Priority recommendations',
    'pricingPage.starterFeature6': 'Monthly monitoring + tracking report',
    'pricingPage.growth': 'Growth',
    'pricingPage.growthSubtitle': 'Full support package',
    'pricingPage.growthPrice': '$4,000',
    'pricingPage.growthPeriod': 'One-shot + $600/mo maintenance',
    'pricingPage.growthFeature1': 'Extended GEO Audit (~150 prompts, 3 languages)',
    'pricingPage.growthFeature2': 'Full audit report',
    'pricingPage.growthFeature3': 'Schema.org — 3 blocks + site implementation',
    'pricingPage.growthFeature4': '18 pillar articles (6 per language, 3 languages)',
    'pricingPage.growthFeature5': 'GEO content plan',
    'pricingPage.growthFeature6': 'Monitoring + optimization + monthly report',
    'pricingPage.custom': 'Custom',
    'pricingPage.customSubtitle': 'Tailored projects',
    'pricingPage.customPrice': '$6,000+',
    'pricingPage.customPeriod': 'Custom pricing',
    'pricingPage.customFeature1': 'Multi-site / multi-brand',
    'pricingPage.customFeature2': 'Volume >20 articles/month',
    'pricingPage.customFeature3': 'Wikipedia strategy',
    'pricingPage.customFeature4': 'Team training',
    'pricingPage.customFeature5': 'GEO press relations',
    'pricingPage.customFeature6': 'Dedicated consultant',
    'pricingPage.faqTitle': 'Frequently Asked Questions',
    'pricingPage.faq1Q': 'What is included in the maintenance?',
    'pricingPage.faq1A': 'Monthly monitoring of your AI visibility, tracking reports, content optimization recommendations, and quarterly strategy reviews.',
    'pricingPage.faq2Q': 'Can I switch plans later?',
    'pricingPage.faq2A': "Yes, you can upgrade or downgrade your plan at any time. We'll prorate the difference.",
    'pricingPage.faq3Q': 'How long until I see results?',
    'pricingPage.faq3A': 'Most clients start seeing increased AI mentions within 4-6 weeks, with significant improvements by month 3.',
    'pricingPage.faq4Q': 'Do you offer a guarantee?',
    'pricingPage.faq4A': 'We guarantee a measurable improvement in your GEO score within 90 days or we work for free until you see results.',
    'pricingPage.customSolution': 'Need a custom solution?',
    'pricingPage.customSolutionSubtitle': 'Contact us for enterprise pricing and custom packages.',
    'pricingPage.contactSales': 'Contact sales',

    // Services Page
    'servicesPage.tagline': 'Our Services',
    'servicesPage.title': 'Everything you need',
    'servicesPage.titleHighlight': 'to be cited by AI.',
    'servicesPage.subtitle': 'From audit to execution, we provide end-to-end GEO services to make your brand visible in the generative AI era.',
    'servicesPage.service1Title': 'GEO Audit',
    'servicesPage.service1Subtitle': 'Complete analysis of your AI visibility',
    'servicesPage.service1Desc': 'We analyze your current visibility across all major AI engines including ChatGPT, Perplexity, Claude, and Google AI. Our comprehensive audit identifies opportunities and provides a detailed roadmap for improvement.',
    'servicesPage.service1Feature1': 'Testing on 50+ key queries',
    'servicesPage.service1Feature2': 'AI competitive analysis',
    'servicesPage.service1Feature3': 'Detailed GEO score',
    'servicesPage.service1Feature4': 'Personalized roadmap',
    'servicesPage.service1Feature5': 'Multi-language support',
    'servicesPage.service1Feature6': 'Quarterly updates',
    'servicesPage.service2Title': 'Technical Optimization',
    'servicesPage.service2Subtitle': 'Implementation of structured data for LLMs',
    'servicesPage.service2Desc': 'We implement advanced Schema.org markup and optimize your site structure to make it easily understandable by Large Language Models. This ensures your content is properly indexed and cited by AI systems.',
    'servicesPage.service2Feature1': 'Advanced Schema.org implementation',
    'servicesPage.service2Feature2': 'AI-friendly content structure',
    'servicesPage.service2Feature3': 'E-E-A-T optimization',
    'servicesPage.service2Feature4': 'Technical performance audit',
    'servicesPage.service2Feature5': 'Knowledge graph integration',
    'servicesPage.service2Feature6': 'Entity optimization',
    'servicesPage.service3Title': 'GEO Content',
    'servicesPage.service3Subtitle': 'Content designed to be cited by AI',
    'servicesPage.service3Desc': 'We create and optimize content specifically designed to be referenced by AI systems. Our content strategy focuses on providing clear, factual, and well-structured information that AI engines love to cite.',
    'servicesPage.service3Feature1': 'Citation-ready articles',
    'servicesPage.service3Feature2': 'Optimized FAQs',
    'servicesPage.service3Feature3': 'Data and sources integration',
    'servicesPage.service3Feature4': 'Structured Q&A format',
    'servicesPage.service3Feature5': 'Entity-rich content',
    'servicesPage.service3Feature6': 'Monthly content calendar',
    'servicesPage.whatsIncluded': "What's included",
    'servicesPage.additionalTitle': 'Additional Services',
    'servicesPage.additionalSubtitle': 'Tailored solutions for enterprise clients',
    'servicesPage.additional1Title': 'Wikipedia Strategy',
    'servicesPage.additional1Desc': 'Build authority through Wikipedia presence',
    'servicesPage.additional2Title': 'Team Training',
    'servicesPage.additional2Desc': 'Educate your team on GEO best practices',
    'servicesPage.additional3Title': 'GEO Press Relations',
    'servicesPage.additional3Desc': 'Get cited in AI-generated news summaries',
    'servicesPage.additional4Title': 'Dedicated Consultant',
    'servicesPage.additional4Desc': 'Personal GEO expert for your brand',
    'servicesPage.readyTitle': 'Ready to get started?',
    'servicesPage.viewPricing': 'View pricing',
    'servicesPage.contactUs': 'Contact us',

    // Legal Page
    'legal.title': 'Legal Notice',
    'legal.intro': 'In accordance with the provisions of Articles 6-III and 19 of French Law No. 2004-575 of June 21, 2004, on Confidence in the Digital Economy (LCEN).',
    'legal.section1Title': '1. Site Publisher',
    'legal.companyName': 'Company Name:',
    'legal.legalStructure': 'Legal Structure:',
    'legal.legalStructureValue': 'Free Zone Limited Liability Company (FZ-LLC)',
    'legal.capital': 'Capital:',
    'legal.capitalValue': 'AED 100,000',
    'legal.regNumber': 'Registration Number:',
    'legal.regNumberValue': '0000004082782',
    'legal.licenceNumber': 'Licence Number:',
    'legal.licenceNumberValue': '47029300',
    'legal.regBody': 'Regulatory Body:',
    'legal.regBodyValue': 'Ras Al Khaimah Economic Zone Authority (RAKEZ)',
    'legal.regAddress': 'Registered Address:',
    'legal.regAddressValue': 'FDRK9297, Compass Building, Al Shohada Road, AL Hamra Industrial Zone-FZ, Ras Al Khaimah, United Arab Emirates',
    'legal.pubDirector': 'Publication Director:',
    'legal.pubDirectorValue': 'Thomas Vignaud, Manager',
    'legal.emailLabel': 'Email:',
    'legal.section2Title': '2. Hosting Provider',
    'legal.section3Title': '3. Intellectual Property',
    'legal.section3P1': 'This entire website is subject to French and international legislation on copyright and intellectual property. All rights of reproduction are reserved, including for downloadable documents and iconographic and photographic representations.',
    'legal.section3P2': 'Reproduction of all or part of this site on any electronic or other medium is strictly prohibited without the express authorization of the publication director.',
    'legal.section4Title': '4. Personal Data Protection',
    'legal.section4P1': 'In accordance with the General Data Protection Regulation (GDPR) and the French Data Protection Act, you have the right to access, rectify, delete and object to personal data concerning you.',
    'legal.section4P2': 'Data collected through contact forms is used solely to respond to your requests and is never shared with third parties without your consent.',
    'legal.section4DataTitle': 'Data collected:',
    'legal.section4Data1': 'Last name and first name',
    'legal.section4Data2': 'Email address',
    'legal.section4Data3': 'Website URL',
    'legal.section4Data4': 'Message and project information',
    'legal.section4Retention': 'Retention period:',
    'legal.section4RetentionValue': 'Data is retained for 3 years from the last contact.',
    'legal.section4Rights': 'To exercise your rights, contact us at:',
    'legal.section5Title': '5. Cookies',
    'legal.section5P1': 'This site does not use tracking or advertising cookies. Only essential technical cookies necessary for the operation of the site may be placed.',
    'legal.section6Title': '6. Limitation of Liability',
    'legal.section6P1': 'The information on this site is as accurate as possible and the site is periodically updated, but may nevertheless contain inaccuracies, omissions or gaps.',
    'legal.section6P2': 'Cited. cannot be held responsible for direct or indirect damages caused to the user\'s equipment when accessing the site, resulting from the use of equipment that does not meet the required technical specifications.',
    'legal.section7Title': '7. Hyperlinks',
    'legal.section7P1': 'This site may contain hyperlinks to other sites. Cited. has no control over these sites and disclaims any responsibility for their content.',
    'legal.section8Title': '8. Applicable Law',
    'legal.section8P1': 'Any dispute in relation to the use of the site citedagency.com is subject to French law. The user acknowledges the exclusive jurisdiction of the French courts.',
    'legal.lastUpdate': 'Last update: January 2025',

    // Footer
    'footer.services': 'Services',
    'footer.pricing': 'Pricing',
    'footer.geoScore': 'GEO Score',
    'footer.blog': 'Blog',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.rights': '© 2026 Cited. All rights reserved.',

    // 404
    '404.title': 'Page not found',
    '404.subtitle': "The page you're looking for doesn't exist or has been moved.",
    '404.home': 'Go home',
    '404.back': 'Go back',
  },
  fr: {
    // Navigation
    'nav.home': 'Accueil',
    'nav.services': 'Services',
    'nav.pricing': 'Tarifs',
    'nav.geoScore': 'Score GEO',
    'nav.schemaAudit': 'Audit Schema',
    'nav.blog': 'Blog',
    'nav.faq': 'FAQ',
    'nav.contact': 'Contact',
    'nav.bookCall': 'Réserver un appel',

    // Hero Section
    'hero.badge': 'Agence GEO — Generative Engine Optimization',
    'hero.title': 'Soyez ',
    'hero.titleHighlight': 'cité',
    'hero.titleEnd': ' par les',
    'hero.titleEnd2': 'moteurs IA.',
    'hero.subtitle': 'Nous optimisons votre visibilité dans ChatGPT, Perplexity et Google AI pour générer des leads qualifiés sans dépendre de la publicité.',
    'hero.cta': 'Tester votre score',
    'hero.ctaSecondary': 'Parler à un expert',
    'hero.stat1Value': '40%',
    'hero.stat1Label': 'Recherches IA',
    'hero.stat2Value': '200M+',
    'hero.stat2Label': 'Utilisateurs ChatGPT',
    'hero.stat3Value': '8x',
    'hero.stat3Label': 'ROI moyen',

    // Stats Section
    'stats.title': 'Le SEO traditionnel ne suffit plus.',
    'stats.subtitle': '40% des recherches passent désormais par l\'IA. Si vous n\'apparaissez pas dans leurs réponses, vous êtes invisible.',
    'stats.stat1Value': '0%',
    'stats.stat1Label': 'Visibilité IA actuelle',
    'stats.stat1Desc': 'La plupart des sites n\'apparaissent jamais dans les réponses de ChatGPT ou Perplexity.',
    'stats.stat2Value': '30%',
    'stats.stat2Label': 'Clics organiques',
    'stats.stat2Desc': 'Les AI Overviews de Google réduisent drastiquement les clics vers les sites web.',
    'stats.stat3Value': '200M',
    'stats.stat3Label': 'Utilisateurs ChatGPT',
    'stats.stat3Desc': 'Un marché massif qui cherche des recommandations. Êtes-vous recommandé ?',
    'stats.cta': 'Vérifier votre score',

    // Services Section
    'services.badge': 'Ce que nous faisons',
    'services.title': 'Une méthodologie éprouvée pour vous rendre visible à l\'ère de l\'',
    'services.titleHighlight': 'IA générative.',
    'services.service1Title': 'Audit GEO',
    'services.service1Subtitle': 'Analyse complète de votre visibilité actuelle dans les moteurs IA et identification des opportunités.',
    'services.service1Feature1': 'Test sur 50+ requêtes clés',
    'services.service1Feature2': 'Analyse concurrentielle IA',
    'services.service1Feature3': 'Score GEO détaillé',
    'services.service1Feature4': 'Feuille de route personnalisée',
    'services.service2Title': 'Optimisation technique',
    'services.service2Subtitle': 'Implémentation des données structurées et optimisations techniques pour les LLMs.',
    'services.service2Feature1': 'Schema.org avancé',
    'services.service2Feature2': 'Structure de contenu IA-friendly',
    'services.service2Feature3': 'Optimisation E-E-A-T',
    'services.service2Feature4': 'Performance technique',
    'services.service3Title': 'Contenu GEO',
    'services.service3Subtitle': 'Création et optimisation de contenu conçu pour être cité par l\'intelligence artificielle.',
    'services.service3Feature1': 'Articles prêts à être cités',
    'services.service3Feature2': 'FAQs optimisées',
    'services.service3Feature3': 'Données et sources',
    'services.service3Feature4': 'Format Q&R structuré',
    'services.viewAll': 'Voir tous les services',

    // Process Section
    'process.badge': 'Notre processus',
    'process.title': 'Une méthodologie claire en 4 étapes',
    'process.titleHighlight': 'pour des résultats mesurables.',
    'process.step1Title': 'Audit',
    'process.step1Desc': 'Analyse de votre visibilité IA actuelle',
    'process.step2Title': 'Stratégie',
    'process.step2Desc': 'Plan d\'action personnalisé',
    'process.step3Title': 'Exécution',
    'process.step3Desc': 'Optimisation technique et contenu',
    'process.step4Title': 'Mesure',
    'process.step4Desc': 'Suivi et amélioration continue',
    'process.cta': 'Vérifier votre score',

    // Results Section
    'results.badge': 'Résultats concrets',
    'results.title': 'Nos clients voient leur visibilité IA',
    'results.titleHighlight': 'décoller en quelques semaines.',
    'results.result1Label': 'Mentions IA moyennes',
    'results.result1Desc': 'Augmentation des citations de marque sur les plateformes IA',
    'results.result2Label': 'Requêtes clés couvertes',
    'results.result2Desc': 'Termes de recherche stratégiques optimisés pour la visibilité',
    'results.result3Label': 'Trafic qualifié',
    'results.result3Desc': 'Croissance de l\'engagement des visiteurs à forte intention',
    'results.result4Label': 'ROI moyen observé',
    'results.result4Desc': 'Multiplicateur du retour sur investissement',

    // CTA Section
    'cta.title': 'Votre marque est-elle ',
    'cta.titleHighlight': 'invisible pour l\'IA ?',
    'cta.subtitle': 'Découvrez votre Score GEO en 30 secondes. Gratuit, sans engagement.',
    'cta.button': 'Vérifier mon score',
    'cta.callTitle': 'Réservez votre appel découverte.',
    'cta.callSubtitle': '30 minutes pour analyser votre situation et définir une stratégie GEO adaptée à vos objectifs.',
    'cta.benefit1': 'Audit de votre visibilité IA actuelle',
    'cta.benefit2': 'Analyse concurrentielle',
    'cta.benefit3': 'Recommandations personnalisées',
    'cta.benefit4': 'Plan d\'action concret',
    'cta.benefit5': '100% gratuit, sans engagement',
    'cta.contactDirect': 'Ou contactez-nous directement :',
    'cta.bookCall': 'Réserver un appel',

    // Pricing Section
    'pricing.badge': 'Nos offres',
    'pricing.title': 'Des offres adaptées à vos ',
    'pricing.titleHighlight': 'besoins et budget.',
    'pricing.popular': 'Populaire',
    'pricing.viewDetails': 'Voir les détails',
    'pricing.hideDetails': 'Masquer les détails',
    'pricing.bookCall': 'Réserver un appel',
    'pricing.starter': 'Starter',
    'pricing.starterSubtitle': 'Démarrez avec le GEO',
    'pricing.starterPrice': '2 000 $',
    'pricing.starterPeriod': 'One-shot + 450 $/mois maintenance',
    'pricing.starterFeature1': 'Audit GEO (5 fournisseurs IA, ~90 prompts, 1 langue)',
    'pricing.starterFeature2': 'Rapport d\'audit avec score GEO + benchmark',
    'pricing.starterFeature3': 'Schema.org — 3 blocs',
    'pricing.starterFeature4': '6 articles piliers optimisés GEO (1 langue)',
    'pricing.starterFeature5': 'Recommandations prioritaires',
    'pricing.starterFeature6': 'Maintenance : suivi mensuel + rapport de tracking',
    'pricing.growth': 'Growth',
    'pricing.growthSubtitle': 'Accompagnement complet',
    'pricing.growthPrice': '4 000 $',
    'pricing.growthPeriod': 'One-shot + 600 $/mois maintenance',
    'pricing.growthFeature1': 'Audit GEO étendu (~150 prompts, 3 langues)',
    'pricing.growthFeature2': 'Rapport d\'audit complet',
    'pricing.growthFeature3': 'Schema.org — 3 blocs + implémentation site',
    'pricing.growthFeature4': '18 articles piliers (6 par langue, 3 langues)',
    'pricing.growthFeature5': 'Plan de contenu GEO',
    'pricing.growthFeature6': 'Maintenance : suivi + optimisation contenu + rapport mensuel',
    'pricing.custom': 'Sur mesure',
    'pricing.customSubtitle': 'Projets sur mesure',
    'pricing.customPrice': '6 000 $+',
    'pricing.customPeriod': 'Sur mesure',
    'pricing.customFeature1': 'Multi-site / multi-marque',
    'pricing.customFeature2': 'Volume >20 articles/mois',
    'pricing.customFeature3': 'Stratégie Wikipédia',
    'pricing.customFeature4': 'Formation d\'équipe',
    'pricing.customFeature5': 'Relations presse GEO',
    'pricing.customFeature6': 'Consultant dédié',

    // Contact Section (form on landing page)
    'contactSection.badge': 'Demande d\'audit gratuit',
    'contactSection.title': 'Remplissez ce formulaire et nous vous répondrons sous ',
    'contactSection.titleHighlight': '24 heures.',
    'contactSection.thankYou': 'Merci !',
    'contactSection.received': 'Nous avons bien reçu votre demande et vous répondrons sous 24 heures.',
    'contactSection.firstName': 'Prénom',
    'contactSection.lastName': 'Nom',
    'contactSection.email': 'Email professionnel',
    'contactSection.website': 'Site web',
    'contactSection.budget': 'Budget mensuel',
    'contactSection.goal': 'Votre objectif principal',
    'contactSection.goalPlaceholder': 'Parlez-nous de vos objectifs et défis...',
    'contactSection.submit': 'Demander mon audit gratuit',
    'contactSection.budgetOption1': 'Sélectionner...',
    'contactSection.budgetOption2': 'Starter — 2 000 $ + 450 $/mois',
    'contactSection.budgetOption3': 'Growth — 4 000 $ + 600 $/mois',
    'contactSection.budgetOption4': 'Sur mesure — à partir de 6 000 $',

    // Contact Page
    'contact.tagline': 'Contact',
    'contact.title': 'Parlons de votre ',
    'contact.titleHighlight': 'visibilité IA.',
    'contact.subtitle': 'Obtenez une consultation gratuite et découvrez comment nous pouvons aider votre marque à être citée par les moteurs IA.',
    'contact.email': 'Email',
    'contact.emailCopied': 'Email copié !',
    'contact.bookCall': 'Réserver un appel',
    'contact.scheduleMeeting': 'Planifier un rendez-vous',
    'contact.formTitle': 'Envoyez-nous un message',
    'contact.formSubtitle': 'Remplissez le formulaire ci-dessous et nous vous répondrons rapidement.',
    'contact.firstName': 'Prénom',
    'contact.lastName': 'Nom',
    'contact.professionalEmail': 'Email professionnel',
    'contact.website': 'Site web',
    'contact.budget': 'Budget mensuel',
    'contact.goal': 'Votre objectif principal',
    'contact.goalPlaceholder': 'Parlez-nous de vos objectifs et défis...',
    'contact.send': 'Envoyer le message',
    'contact.sending': 'Envoi en cours...',
    'contact.thankYou': 'Merci !',
    'contact.received': 'Nous avons bien reçu votre message et vous répondrons sous 24 heures.',
    'contact.error': 'Une erreur est survenue. Veuillez réessayer.',
    'contact.budgetOption1': 'Sélectionner...',
    'contact.budgetOption2': 'Starter — 2 000 $ + 450 $/mois',
    'contact.budgetOption3': 'Growth — 4 000 $ + 600 $/mois',
    'contact.budgetOption4': 'Sur mesure — à partir de 6 000 $',

    // GEO Score Page
    'geoScore.tagline': 'Score GEO',
    'geoScore.title': 'Quelle est votre visibilité sur les ',
    'geoScore.titleHighlight': 'moteurs IA ?',
    'geoScore.subtitle': 'Obtenez votre Score GEO gratuit en quelques secondes. Découvrez si votre site est optimisé pour ChatGPT, Perplexity et les autres systèmes IA.',
    'geoScore.brandLabel': 'Nom de votre marque / entreprise',
    'geoScore.brandPlaceholder': 'Ex : Cited, Nike, Salesforce...',
    'geoScore.industryLabel': 'Secteur d\'activité',
    'geoScore.industrySelect': 'Sélectionnez votre secteur',
    'geoScore.websiteLabel': 'Site web',
    'geoScore.websiteOptional': '(optionnel)',
    'geoScore.websiteHint': 'Nous l\'utiliserons pour affiner l\'analyse',
    'geoScore.websitePlaceholder': 'https://votre-site.com',
    'geoScore.analyze': 'Analyser ma visibilité IA',
    'geoScore.analyzing': 'Analyse en cours...',
    'geoScore.getAudit': 'Obtenir un audit détaillé',
    'geoScore.checkAnother': 'Analyser une autre marque',
    'geoScore.scoreExcellent': 'Excellent ! Votre site est bien optimisé pour l\'IA.',
    'geoScore.scoreGood': 'Bon début, mais il y a des améliorations possibles.',
    'geoScore.scoreNeedsWork': 'Votre site nécessite une optimisation significative pour la visibilité IA.',
    'geoScore.whatWeCheck': 'Ce que nous vérifions',
    'geoScore.weight': 'Poids',
    'geoScore.improveTitle': 'Vous souhaitez améliorer votre score ?',
    'geoScore.improveSubtitle': 'Nos experts peuvent vous aider à optimiser votre site pour une visibilité IA maximale.',
    'geoScore.explorServices': 'Découvrir nos services',
    'geoScore.industryTechnology': 'Technologie',
    'geoScore.industrySaas': 'SaaS',
    'geoScore.industryEcommerce': 'E-commerce',
    'geoScore.industryFinance': 'Finance',
    'geoScore.industryHealthcare': 'Santé',
    'geoScore.industryConsulting': 'Conseil',
    'geoScore.industryAgency': 'Agence',
    'geoScore.industryEducation': 'Éducation',
    'geoScore.industryRealEstate': 'Immobilier',
    'geoScore.industryOther': 'Autre',

    // Schema Audit Page
    'schemaAudit.tagline': 'Audit Schema',
    'schemaAudit.title': 'Rendez votre contenu ',
    'schemaAudit.titleHighlight': 'compréhensible par l\'IA.',
    'schemaAudit.subtitle': 'Le balisage Schema.org est la base de la visibilité IA. Nous auditons, implémentons et optimisons les données structurées pour aider les moteurs IA à comprendre et citer votre contenu.',
    'schemaAudit.analyzeTitle': 'Analysez votre Schema.org',
    'schemaAudit.analyzeSubtitle': 'Entrez votre URL pour obtenir un audit schema gratuit',
    'schemaAudit.urlPlaceholder': 'https://votre-site.com',
    'schemaAudit.analyze': 'Analyser Schema.org',
    'schemaAudit.analyzing': 'Analyse en cours...',
    'schemaAudit.stepFetching': 'Récupération de la page',
    'schemaAudit.stepDetecting': 'Détection des schemas',
    'schemaAudit.stepAnalyzing': 'Analyse du balisage',
    'schemaAudit.stepCalculating': 'Calcul du score',
    'schemaAudit.scoreExcellent': 'Excellent ! Votre Schema.org est bien implémenté.',
    'schemaAudit.scoreGood': 'Bon début, mais il y a des améliorations possibles.',
    'schemaAudit.scoreNeedsWork': 'Votre site nécessite une optimisation Schema.org significative.',
    'schemaAudit.schemasDetected': 'Schemas détectés',
    'schemaAudit.issuesFound': 'Problèmes trouvés',
    'schemaAudit.emailReportText': 'Recevez un rapport PDF détaillé par email',
    'schemaAudit.emailPlaceholder': 'votre@email.com',
    'schemaAudit.sendReport': 'Envoyer le rapport',
    'schemaAudit.reportSent': 'Rapport envoyé à',
    'schemaAudit.bookCall': 'Réserver un appel gratuit',
    'schemaAudit.analyzeAnother': 'Analyser une autre URL',
    'schemaAudit.featuresTitle1': 'Implémentation Schema.org',
    'schemaAudit.featuresDesc1': 'Balisage complet des données structurées pour la compréhension IA',
    'schemaAudit.featuresTitle2': 'Validation & Tests',
    'schemaAudit.featuresDesc2': 'Assurez-vous que votre balisage est sans erreur et optimisé',
    'schemaAudit.featuresTitle3': 'Impact sur la performance',
    'schemaAudit.featuresDesc3': 'Mesurez l\'effet sur la visibilité IA',
    'schemaAudit.featuresTitle4': 'Implémentation rapide',
    'schemaAudit.featuresDesc4': 'Démarrez en quelques jours, pas en semaines',
    'schemaAudit.schemaTypesTitle': 'Types de Schema que nous implémentons',
    'schemaAudit.schemaTypesSubtitle': 'Couverture complète de tous les types de données structurées pertinents',
    'schemaAudit.processTitle': 'Notre processus',
    'schemaAudit.processSubtitle': 'Une approche systématique de l\'optimisation Schema.org',
    'schemaAudit.processStep1': 'Audit',
    'schemaAudit.processStep1Desc': 'Analyser l\'implémentation Schema.org actuelle',
    'schemaAudit.processStep2': 'Stratégie',
    'schemaAudit.processStep2Desc': 'Identifier les opportunités de balisage manquantes',
    'schemaAudit.processStep3': 'Implémentation',
    'schemaAudit.processStep3Desc': 'Ajouter et optimiser les données structurées',
    'schemaAudit.processStep4': 'Validation',
    'schemaAudit.processStep4Desc': 'Tester et vérifier tout le balisage',
    'schemaAudit.pricingTitle': 'Tarifs',
    'schemaAudit.pricingSubtitle': 'Choisissez l\'offre qui correspond à vos besoins',
    'schemaAudit.pricingStarter': 'Starter',
    'schemaAudit.pricingStarterDesc': '3 types de schema',
    'schemaAudit.pricingStarterPrice': '1 500 $',
    'schemaAudit.pricingGrowth': 'Growth',
    'schemaAudit.pricingGrowthDesc': '8 types de schema',
    'schemaAudit.pricingGrowthPrice': '3 000 $',
    'schemaAudit.pricingEnterprise': 'Entreprise',
    'schemaAudit.pricingEnterpriseDesc': 'Types illimités',
    'schemaAudit.pricingEnterprisePrice': 'Sur mesure',
    'schemaAudit.mostPopular': 'Le plus populaire',
    'schemaAudit.getStarted': 'Commencer',
    'schemaAudit.ctaTitle': 'Prêt à optimiser votre Schema.org ?',
    'schemaAudit.ctaSubtitle': 'Obtenez un audit gratuit de votre implémentation de données structurées.',
    'schemaAudit.ctaButton': 'Demander un audit gratuit',

    // FAQ Page
    'faq.tagline': 'FAQ',
    'faq.title': 'Questions ',
    'faq.titleHighlight': 'fréquentes.',
    'faq.subtitle': 'Tout ce que vous devez savoir sur le GEO et nos services.',
    'faq.catGeneral': 'Général',
    'faq.catServices': 'Services',
    'faq.catPricing': 'Tarifs',
    'faq.catTechnical': 'Technique',
    'faq.general1Q': 'Qu\'est-ce que le Generative Engine Optimization (GEO) ?',
    'faq.general1A': 'Le GEO est la pratique d\'optimisation de votre site web et contenu pour être visible et cité par les moteurs IA comme ChatGPT, Perplexity, Claude et Google AI. Contrairement au SEO traditionnel qui se concentre sur le classement dans les résultats de recherche, le GEO se concentre sur le référencement dans les réponses générées par l\'IA.',
    'faq.general2Q': 'En quoi le GEO diffère-t-il du SEO ?',
    'faq.general2A': 'Alors que le SEO se concentre sur le classement dans les pages de résultats des moteurs de recherche, le GEO se concentre sur la citation par les systèmes IA. Cela nécessite des stratégies différentes incluant l\'implémentation de données structurées, l\'optimisation des entités et la structuration du contenu pour la compréhension par l\'IA.',
    'faq.general3Q': 'Pourquoi ai-je besoin du GEO ?',
    'faq.general3A': '40% des recherches passent désormais par les systèmes IA. Si votre marque n\'est pas visible dans les réponses IA, vous manquez une opportunité massive d\'atteindre des clients potentiels. Le GEO garantit que votre entreprise est recommandée par les systèmes IA.',
    'faq.services1Q': 'Quels services proposez-vous ?',
    'faq.services1A': 'Nous proposons trois services principaux : Audit GEO (analyse de votre visibilité IA), Optimisation Technique (implémentation Schema.org et structure du site), et Contenu GEO (création de contenu optimisé pour l\'IA). Nous proposons également des solutions entreprise sur mesure.',
    'faq.services2Q': 'Combien de temps faut-il pour voir des résultats ?',
    'faq.services2A': 'La plupart des clients commencent à voir une augmentation des mentions IA dans les 4 à 6 semaines, avec des améliorations significatives au 3ème mois. Le délai dépend de votre point de départ et de l\'étendue du travail.',
    'faq.services3Q': 'Travaillez-vous avec tous les secteurs ?',
    'faq.services3A': 'Nous travaillons avec les entreprises B2B, e-commerce, SaaS, services professionnels et plus encore. Notre méthodologie est adaptable à tout secteur qui dépend de la visibilité organique.',
    'faq.pricing1Q': 'Combien coûte l\'optimisation GEO ?',
    'faq.pricing1A': 'Notre offre Starter commence à 2 000 $ + 450 $/mois de maintenance. L\'offre Growth est à 4 000 $ + 600 $/mois. Nous proposons également des solutions entreprise sur mesure. Contactez-nous pour un devis personnalisé.',
    'faq.pricing2Q': 'Qu\'est-ce qui est inclus dans la maintenance ?',
    'faq.pricing2A': 'La maintenance inclut le suivi mensuel de votre visibilité IA, les rapports de tracking, les recommandations d\'optimisation de contenu et les revues stratégiques trimestrielles pour assurer une amélioration continue.',
    'faq.pricing3Q': 'Y a-t-il un contrat minimum ?',
    'faq.pricing3A': 'Notre engagement initial comprend des frais de mise en place uniques plus un contrat de maintenance minimum de 6 mois. Après cela, vous pouvez résilier avec un préavis de 30 jours.',
    'faq.technical1Q': 'Qu\'est-ce que Schema.org et pourquoi est-ce important ?',
    'faq.technical1A': 'Schema.org est un vocabulaire standardisé pour le balisage de données structurées. Il aide les systèmes IA à comprendre le contexte, les entités et les relations de votre contenu, le rendant plus susceptible d\'être cité dans les réponses générées par l\'IA.',
    'faq.technical2Q': 'Dois-je modifier mon site web ?',
    'faq.technical2A': 'Selon les résultats de l\'audit, nous pouvons recommander des modifications techniques pour améliorer la visibilité IA. Celles-ci impliquent généralement l\'ajout de données structurées, l\'optimisation de la structure du contenu et l\'amélioration des performances du site.',
    'faq.technical3Q': 'Le GEO affectera-t-il mon SEO traditionnel ?',
    'faq.technical3A': 'Le GEO et le SEO sont complémentaires. De nombreuses optimisations GEO (comme le balisage Schema.org) bénéficient également au SEO traditionnel. Nous nous assurons que toutes les modifications maintiennent ou améliorent vos classements de recherche existants.',
    'faq.stillQuestions': 'Vous avez encore des questions ?',
    'faq.stillQuestionsSubtitle': 'Vous ne trouvez pas la réponse que vous cherchez ? Notre équipe est là pour vous aider.',
    'faq.contactUs': 'Contactez-nous',

    // Blog Page
    'blog.tagline': 'Blog',
    'blog.title': 'Analyses sur la ',
    'blog.titleHighlight': 'visibilité IA.',
    'blog.subtitle': 'Les dernières stratégies, études de cas et analyses sur l\'optimisation pour les moteurs IA génératifs.',
    'blog.featured': 'À la une',
    'blog.readArticle': 'Lire l\'article',
    'blog.latestArticles': 'Derniers articles',
    'blog.catAll': 'Tous',
    'blog.catGeoBasics': 'Bases GEO',
    'blog.catTechnical': 'Technique',
    'blog.catImplementation': 'Implémentation',
    'blog.catCaseStudy': 'Étude de cas',
    'blog.catIndustry': 'Industrie',
    'blog.stayUpdated': 'Restez informé',
    'blog.stayUpdatedSubtitle': 'Recevez les dernières analyses GEO directement dans votre boîte mail.',
    'blog.emailPlaceholder': 'Entrez votre email',
    'blog.subscribe': 'S\'abonner',
    'blog.subscribing': 'Inscription...',
    'blog.subscribed': 'Merci pour votre inscription !',
    'blog.article1Title': 'Qu\'est-ce que le Generative Engine Optimization (GEO) ?',
    'blog.article1Excerpt': 'Découvrez comment le GEO diffère du SEO traditionnel et pourquoi il est important pour votre entreprise à l\'ère de l\'IA.',
    'blog.article1Category': 'Bases GEO',
    'blog.article1ReadTime': '5 min de lecture',
    'blog.article1Date': '15 jan. 2026',
    'blog.article2Title': 'Comment ChatGPT cite les sites web : une analyse technique',
    'blog.article2Excerpt': 'Comprendre les mécanismes derrière la citation par l\'IA et comment optimiser votre contenu pour une visibilité maximale.',
    'blog.article2Category': 'Technique',
    'blog.article2ReadTime': '8 min de lecture',
    'blog.article2Date': '12 jan. 2026',
    'blog.article3Title': 'Schema.org pour l\'IA : le guide complet',
    'blog.article3Excerpt': 'Apprenez à implémenter les données structurées qui aident les systèmes IA à comprendre et citer votre contenu.',
    'blog.article3Category': 'Implémentation',
    'blog.article3ReadTime': '12 min de lecture',
    'blog.article3Date': '8 jan. 2026',
    'blog.article4Title': 'Étude de cas : comment nous avons augmenté les mentions IA de 340%',
    'blog.article4Excerpt': 'Une analyse détaillée de notre stratégie et des résultats obtenus pour une entreprise SaaS B2B.',
    'blog.article4Category': 'Étude de cas',
    'blog.article4ReadTime': '6 min de lecture',
    'blog.article4Date': '5 jan. 2026',
    'blog.article5Title': 'L\'avenir de la recherche : IA vs SEO traditionnel',
    'blog.article5Excerpt': 'Pourquoi le SEO traditionnel ne suffit plus et comment se préparer à l\'avenir centré sur l\'IA.',
    'blog.article5Category': 'Industrie',
    'blog.article5ReadTime': '7 min de lecture',
    'blog.article5Date': '2 jan. 2026',
    'blog.article6Title': 'Optimisation E-E-A-T pour les grands modèles de langage',
    'blog.article6Excerpt': 'Comment construire des signaux d\'autorité que les systèmes IA reconnaissent et auxquels ils font confiance.',
    'blog.article6Category': 'Technique',
    'blog.article6ReadTime': '10 min de lecture',
    'blog.article6Date': '28 déc. 2025',

    // Pricing Page
    'pricingPage.tagline': 'Tarifs',
    'pricingPage.title': 'Des tarifs simples et ',
    'pricingPage.titleHighlight': 'transparents.',
    'pricingPage.subtitle': 'Choisissez l\'offre qui correspond à vos besoins. Toutes les offres incluent notre méthodologie GEO.',
    'pricingPage.mostPopular': 'Le plus populaire',
    'pricingPage.getStarted': 'Commencer',
    'pricingPage.starter': 'Starter',
    'pricingPage.starterSubtitle': 'Démarrez avec le GEO',
    'pricingPage.starterPrice': '2 000 $',
    'pricingPage.starterPeriod': 'One-shot + 450 $/mois maintenance',
    'pricingPage.starterFeature1': 'Audit GEO (5 fournisseurs IA, ~90 prompts, 1 langue)',
    'pricingPage.starterFeature2': 'Rapport d\'audit avec score GEO + benchmark',
    'pricingPage.starterFeature3': 'Schema.org — 3 blocs',
    'pricingPage.starterFeature4': '6 articles piliers optimisés GEO (1 langue)',
    'pricingPage.starterFeature5': 'Recommandations prioritaires',
    'pricingPage.starterFeature6': 'Suivi mensuel + rapport de tracking',
    'pricingPage.growth': 'Growth',
    'pricingPage.growthSubtitle': 'Accompagnement complet',
    'pricingPage.growthPrice': '4 000 $',
    'pricingPage.growthPeriod': 'One-shot + 600 $/mois maintenance',
    'pricingPage.growthFeature1': 'Audit GEO étendu (~150 prompts, 3 langues)',
    'pricingPage.growthFeature2': 'Rapport d\'audit complet',
    'pricingPage.growthFeature3': 'Schema.org — 3 blocs + implémentation site',
    'pricingPage.growthFeature4': '18 articles piliers (6 par langue, 3 langues)',
    'pricingPage.growthFeature5': 'Plan de contenu GEO',
    'pricingPage.growthFeature6': 'Suivi + optimisation contenu + rapport mensuel',
    'pricingPage.custom': 'Sur mesure',
    'pricingPage.customSubtitle': 'Projets sur mesure',
    'pricingPage.customPrice': '6 000 $+',
    'pricingPage.customPeriod': 'Tarification sur mesure',
    'pricingPage.customFeature1': 'Multi-site / multi-marque',
    'pricingPage.customFeature2': 'Volume >20 articles/mois',
    'pricingPage.customFeature3': 'Stratégie Wikipédia',
    'pricingPage.customFeature4': 'Formation d\'équipe',
    'pricingPage.customFeature5': 'Relations presse GEO',
    'pricingPage.customFeature6': 'Consultant dédié',
    'pricingPage.faqTitle': 'Questions fréquentes',
    'pricingPage.faq1Q': 'Qu\'est-ce qui est inclus dans la maintenance ?',
    'pricingPage.faq1A': 'Le suivi mensuel de votre visibilité IA, les rapports de tracking, les recommandations d\'optimisation de contenu et les revues stratégiques trimestrielles.',
    'pricingPage.faq2Q': 'Puis-je changer d\'offre plus tard ?',
    'pricingPage.faq2A': 'Oui, vous pouvez passer à une offre supérieure ou inférieure à tout moment. Nous calculerons la différence au prorata.',
    'pricingPage.faq3Q': 'Combien de temps avant de voir des résultats ?',
    'pricingPage.faq3A': 'La plupart des clients commencent à voir une augmentation des mentions IA dans les 4 à 6 semaines, avec des améliorations significatives au 3ème mois.',
    'pricingPage.faq4Q': 'Offrez-vous une garantie ?',
    'pricingPage.faq4A': 'Nous garantissons une amélioration mesurable de votre score GEO dans les 90 jours ou nous travaillons gratuitement jusqu\'à ce que vous voyiez des résultats.',
    'pricingPage.customSolution': 'Besoin d\'une solution sur mesure ?',
    'pricingPage.customSolutionSubtitle': 'Contactez-nous pour des tarifs entreprise et des offres personnalisées.',
    'pricingPage.contactSales': 'Contacter les ventes',

    // Services Page
    'servicesPage.tagline': 'Nos services',
    'servicesPage.title': 'Tout ce dont vous avez besoin',
    'servicesPage.titleHighlight': 'pour être cité par l\'IA.',
    'servicesPage.subtitle': 'De l\'audit à l\'exécution, nous fournissons des services GEO de bout en bout pour rendre votre marque visible à l\'ère de l\'IA générative.',
    'servicesPage.service1Title': 'Audit GEO',
    'servicesPage.service1Subtitle': 'Analyse complète de votre visibilité IA',
    'servicesPage.service1Desc': 'Nous analysons votre visibilité actuelle sur tous les principaux moteurs IA, y compris ChatGPT, Perplexity, Claude et Google AI. Notre audit complet identifie les opportunités et fournit une feuille de route détaillée pour l\'amélioration.',
    'servicesPage.service1Feature1': 'Test sur 50+ requêtes clés',
    'servicesPage.service1Feature2': 'Analyse concurrentielle IA',
    'servicesPage.service1Feature3': 'Score GEO détaillé',
    'servicesPage.service1Feature4': 'Feuille de route personnalisée',
    'servicesPage.service1Feature5': 'Support multilingue',
    'servicesPage.service1Feature6': 'Mises à jour trimestrielles',
    'servicesPage.service2Title': 'Optimisation technique',
    'servicesPage.service2Subtitle': 'Implémentation des données structurées pour les LLMs',
    'servicesPage.service2Desc': 'Nous implémentons le balisage Schema.org avancé et optimisons la structure de votre site pour le rendre facilement compréhensible par les grands modèles de langage. Cela garantit que votre contenu est correctement indexé et cité par les systèmes IA.',
    'servicesPage.service2Feature1': 'Implémentation avancée Schema.org',
    'servicesPage.service2Feature2': 'Structure de contenu IA-friendly',
    'servicesPage.service2Feature3': 'Optimisation E-E-A-T',
    'servicesPage.service2Feature4': 'Audit de performance technique',
    'servicesPage.service2Feature5': 'Intégration Knowledge Graph',
    'servicesPage.service2Feature6': 'Optimisation des entités',
    'servicesPage.service3Title': 'Contenu GEO',
    'servicesPage.service3Subtitle': 'Contenu conçu pour être cité par l\'IA',
    'servicesPage.service3Desc': 'Nous créons et optimisons du contenu spécifiquement conçu pour être référencé par les systèmes IA. Notre stratégie de contenu se concentre sur la fourniture d\'informations claires, factuelles et bien structurées que les moteurs IA adorent citer.',
    'servicesPage.service3Feature1': 'Articles prêts à être cités',
    'servicesPage.service3Feature2': 'FAQs optimisées',
    'servicesPage.service3Feature3': 'Intégration de données et sources',
    'servicesPage.service3Feature4': 'Format Q&R structuré',
    'servicesPage.service3Feature5': 'Contenu riche en entités',
    'servicesPage.service3Feature6': 'Calendrier éditorial mensuel',
    'servicesPage.whatsIncluded': 'Ce qui est inclus',
    'servicesPage.additionalTitle': 'Services additionnels',
    'servicesPage.additionalSubtitle': 'Solutions sur mesure pour les clients entreprise',
    'servicesPage.additional1Title': 'Stratégie Wikipédia',
    'servicesPage.additional1Desc': 'Construisez votre autorité via une présence Wikipédia',
    'servicesPage.additional2Title': 'Formation d\'équipe',
    'servicesPage.additional2Desc': 'Formez votre équipe aux bonnes pratiques GEO',
    'servicesPage.additional3Title': 'Relations presse GEO',
    'servicesPage.additional3Desc': 'Soyez cité dans les résumés d\'actualités générés par l\'IA',
    'servicesPage.additional4Title': 'Consultant dédié',
    'servicesPage.additional4Desc': 'Un expert GEO personnel pour votre marque',
    'servicesPage.readyTitle': 'Prêt à commencer ?',
    'servicesPage.viewPricing': 'Voir les tarifs',
    'servicesPage.contactUs': 'Nous contacter',

    // Legal Page
    'legal.title': 'Mentions légales',
    'legal.intro': 'Conformément aux dispositions des articles 6-III et 19 de la Loi n°2004-575 du 21 juin 2004 pour la Confiance dans l\'économie numérique (LCEN).',
    'legal.section1Title': '1. Éditeur du site',
    'legal.companyName': 'Raison sociale :',
    'legal.legalStructure': 'Forme juridique :',
    'legal.legalStructureValue': 'Free Zone Limited Liability Company (FZ-LLC)',
    'legal.capital': 'Capital :',
    'legal.capitalValue': '100 000 AED',
    'legal.regNumber': 'Numéro d\'enregistrement :',
    'legal.regNumberValue': '0000004082782',
    'legal.licenceNumber': 'Numéro de licence :',
    'legal.licenceNumberValue': '47029300',
    'legal.regBody': 'Organisme de régulation :',
    'legal.regBodyValue': 'Ras Al Khaimah Economic Zone Authority (RAKEZ)',
    'legal.regAddress': 'Adresse du siège :',
    'legal.regAddressValue': 'FDRK9297, Compass Building, Al Shohada Road, AL Hamra Industrial Zone-FZ, Ras Al Khaimah, Émirats Arabes Unis',
    'legal.pubDirector': 'Directeur de la publication :',
    'legal.pubDirectorValue': 'Thomas Vignaud, Gérant',
    'legal.emailLabel': 'Email :',
    'legal.section2Title': '2. Hébergeur',
    'legal.section3Title': '3. Propriété intellectuelle',
    'legal.section3P1': 'L\'ensemble de ce site relève de la législation française et internationale sur le droit d\'auteur et la propriété intellectuelle. Tous les droits de reproduction sont réservés, y compris pour les documents téléchargeables et les représentations iconographiques et photographiques.',
    'legal.section3P2': 'La reproduction de tout ou partie de ce site sur un support électronique ou autre est formellement interdite sauf autorisation expresse du directeur de la publication.',
    'legal.section4Title': '4. Protection des données personnelles',
    'legal.section4P1': 'Conformément au Règlement Général sur la Protection des Données (RGPD) et à la loi Informatique et Libertés, vous disposez d\'un droit d\'accès, de rectification, de suppression et d\'opposition aux données personnelles vous concernant.',
    'legal.section4P2': 'Les données collectées via les formulaires de contact sont utilisées uniquement pour répondre à vos demandes et ne sont jamais transmises à des tiers sans votre consentement.',
    'legal.section4DataTitle': 'Données collectées :',
    'legal.section4Data1': 'Nom et prénom',
    'legal.section4Data2': 'Adresse email',
    'legal.section4Data3': 'URL du site web',
    'legal.section4Data4': 'Message et informations sur votre projet',
    'legal.section4Retention': 'Durée de conservation :',
    'legal.section4RetentionValue': 'Les données sont conservées pendant 3 ans à compter du dernier contact.',
    'legal.section4Rights': 'Pour exercer vos droits, contactez-nous à :',
    'legal.section5Title': '5. Cookies',
    'legal.section5P1': 'Ce site n\'utilise pas de cookies de tracking ou de publicité. Seuls des cookies techniques essentiels au fonctionnement du site peuvent être déposés.',
    'legal.section6Title': '6. Limitation de responsabilité',
    'legal.section6P1': 'Les informations contenues sur ce site sont aussi précises que possible et le site est périodiquement mis à jour, mais peut toutefois contenir des inexactitudes, des omissions ou des lacunes.',
    'legal.section6P2': 'Cited. ne pourra être tenu responsable des dommages directs et indirects causés au matériel de l\'utilisateur lors de l\'accès au site, résultant de l\'utilisation d\'un matériel ne répondant pas aux spécifications techniques requises.',
    'legal.section7Title': '7. Liens hypertextes',
    'legal.section7P1': 'Ce site peut contenir des liens hypertextes vers d\'autres sites. Cited. n\'exerce aucun contrôle sur ces sites et décline toute responsabilité quant à leur contenu.',
    'legal.section8Title': '8. Droit applicable',
    'legal.section8P1': 'Tout litige en relation avec l\'utilisation du site citedagency.com est soumis au droit français. L\'utilisateur reconnaît la compétence exclusive des tribunaux français.',
    'legal.lastUpdate': 'Dernière mise à jour : Janvier 2025',

    // Footer
    'footer.services': 'Services',
    'footer.pricing': 'Tarifs',
    'footer.geoScore': 'Score GEO',
    'footer.blog': 'Blog',
    'footer.faq': 'FAQ',
    'footer.contact': 'Contact',
    'footer.legal': 'Mentions légales',
    'footer.rights': '© 2026 Cited. Tous droits réservés.',

    // 404
    '404.title': 'Page non trouvée',
    '404.subtitle': 'La page que vous recherchez n\'existe pas ou a été déplacée.',
    '404.home': 'Retour à l\'accueil',
    '404.back': 'Retour',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
